Repository hmcts/juror-public, pull requests merged in 2024-06, with the labels that each got.

#189 Replace grunt with webpack
  Gruntfile.js
  client/js/main.js
  client/scss/custom-components/ds-datepicker.scss
  client/scss/custom-components/index.scss
  client/scss/main.scss
  client/templates/layouts/default-gds.njk
  nodemon.json
  package.json
  webpack.config.js
  webpack/htmlWebpack.js
  webpack/scss.js
  webpack/translation.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-public-pr-189

#193 JDB-5592 - Update eslint package and config
  eslint.config.js
  eslint.unignore.js
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-public-pr-193

#196 JDB-5592 - Remove old eslint config
  .eslintignore
  .eslintrc
Labels: ns:juror, prd:juror, rel:juror-public-pr-196

#197 JDB-5277 - Axios health actuator
  server/objects/health.js
  server/routes/actuator/actuator.controller.js
  server/routes/actuator/index.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-197

#198 JDB-5593 - Remove redis temp logging / update session save
  server/routes/steps/03-qualify/qualify.controller.js
  server/routes/steps/06-assistance/assistance.controller.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-198

#201 JDB-5586 - Login summons date passed page
  client/js/i18n/cy/LOGIN_PAGE.json
  client/js/i18n/en/LOGIN_PAGE.json
  client/templates/includes/contact-details.njk
  client/templates/steps/01-login/login.njk
  client/templates/steps/01-login/summons-date.njk
  server/routes/index.js
  server/routes/steps/01-login/index.js
  server/routes/steps/01-login/login.controller.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-201

#206 JDB-5594 - Expense calc FACT link Welsh translation
  client/js/i18n/cy/EXPENSE_CALCULATOR.json
  client/js/i18n/en/EXPENSE_CALCULATOR.json
Labels: ns:juror, prd:juror, rel:juror-public-pr-206

#207 JDB-5573 - Refactor 3rd party juror details API calls
  server/routes/branches/02-third-party-reason/third-party-reason.controller.js
  server/routes/branches/03-third-party-personal-details/index.js
  server/routes/branches/03-third-party-personal-details/third-party-personal-details.controller.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-207

#209 JDB-5556-2 - Cookie policy Welsh content update
  client/js/i18n/cy/COOKIE_SETTINGS_PAGE.json
  client/js/i18n/en/COOKIE_SETTINGS_PAGE.json
Labels: ns:juror, prd:juror, rel:juror-public-pr-209

#213 JDB-5602 - Postcode regex alert
  server/routes/steps/01-login/login.controller.js
  server/routes/steps/02-your-details/your-details.controller.js
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-public-pr-213
