Repository hmcts/juror-public, pull requests merged in 2024-05, with the labels that each got.

#159 JDB-5277 - Axios expenses calc
  server/objects/expenseCalculator.js
  server/routes/expense-calculator/confirm-information/confirm-information.controller.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-159

#160 JDB-5564 - Refactor Utils RA submission
  server/lib/utils.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-160

#170 update dockerignore & remove grunt-sonar-runner
  .dockerignore
  package.json
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-public-pr-170

#171 JDB-5584 - Grunt node dependencies
  Gruntfile.js
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-public-pr-171

#174 JDB-5277 - Axios juror details / app-settings
  server/components/pcqService/index.js
  server/objects/appSettings.js
  server/objects/axios-instance.js
  server/objects/juror.js
  server/routes/branches/03-third-party-personal-details/third-party-personal-details.controller.js
  server/routes/steps/02-your-details/your-details.controller.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-174

#177 JDB-5277 - Axios PCQ service
  server/components/pcqService/index.js
  server/objects/pcqService.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-177

#181 JDB-5578 - Update express config / session name
  server/config/express.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-181

#184 JDB-5585 - Expense calc FACT link url (EN)
  client/js/i18n/cy/EXPENSE_CALCULATOR.json
  client/js/i18n/en/EXPENSE_CALCULATOR.json
Labels: ns:juror, prd:juror, rel:juror-public-pr-184

#185 JDB-5277 - Axios juror response post
  server/objects/response.js
  server/routes/steps/07-confirm-information/confirm-information.controller.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-185

#186 lock azure provider
  infrastructure/state.tf
Labels: ns:juror, prd:juror, stg/add-or-update, prod/no-changes

#187 JDB-5556 - Cookie policy update for Dynatrace
  client/js/i18n/cy/COOKIE_PAGE.json
  client/js/i18n/cy/COOKIE_SETTINGS_PAGE.json
  client/js/i18n/en/COOKIE_PAGE.json
  client/js/i18n/en/COOKIE_SETTINGS_PAGE.json
  client/templates/cookie-settings.njk
  client/templates/cookies.njk
  client/templates/layouts/expense-calculator-template.njk
  client/templates/layouts/template.njk
  server/routes/cookies/cookie.controller.js
  server/routes/cookies/index.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-187

#190 JDB-5567 - Rate limiting config
  charts/juror-public/Chart.yaml
  charts/juror-public/values.yaml
  package.json
  server/config/environment/index.js
  server/config/express.js
  server/lib/rate-limit-config.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-public-pr-190
