Repository hmcts/juror-public, pull requests merged in 2024-04, with the labels that each got.

#137 JDB-5551 - Secure cookies in production env
  server/config/express.js
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-public-pr-137

#138 JDB-5458 - Update excusal guidance content
  client/js/i18n/cy/EXCUSAL_PAGE.json
  client/js/i18n/en/EXCUSAL_PAGE.json
Labels: ns:juror, prd:juror, rel:juror-public-pr-138

#139 JDB-5524-1 - Crown Logo update for expense calculator
  client/templates/layouts/expense-calculator-template.njk
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-public-pr-139

#140 JDB-5530 - PDF/HTML download logo images
  client/assets/images/hmcts-logo-cy.png
  client/assets/images/hmcts-logo-en.png
  client/assets/images/pdflogo-cy.jpg
  client/assets/images/pdflogo.jpg
  client/js/i18n/cy/PDF.json
  client/js/i18n/en/PDF.json
  client/templates/steps/08-confirmation/response-html/index.njk
Labels: ns:juror, prd:juror, rel:juror-public-pr-140

#141 JDB-5550 - Public 3rd Person login ‘court date already passed’ error …
  server/components/errors/message-mapping_cy.js
  server/components/errors/message-mapping_en.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-141

#142 JDB-5559 - Public FE - SameSite session cookie attribute
  server/config/express.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-142

#143 JDB-5531 - Check Answers hearing date/time deprecation warning
  server/routes/steps/07-confirm-information/confirm-information.controller.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-143

#146 JDB-5555 - Dynatrace integration
  charts/juror-public/Chart.yaml
  charts/juror-public/values.yaml
  client/templates/layouts/template.njk
  config/development.json
  config/production.json
  config/test.json
  server/config/express.js
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-public-pr-146

#154 remove unneeded suppressions
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-public-pr-154

#157 JDB-5277 - Axios login/auth
  server/components/auth/index.js
  server/objects/auth.js
  server/objects/axios-instance.js
  server/routes/steps/01-login/login.controller.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-157

#158 JDB-5277 - Axios / deferral holiday
  server/objects/deferralHoliday.js
  server/routes/steps/04-confirm-date/deferr/defer-check.controller.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-158
