Repository hmcts/juror-public, pull requests merged in 2024-03, with the labels that each got.

#104 alter appinsights trigger
  server/lib/appinsights.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-104

#107 Change the way app-insights gets triggered
  server/lib/appinsights.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-107

#109 update appinsights
  server/lib/appinsights.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-109

#111 alter insights
  config/development.json
  config/production.json
  config/test.json
  server/lib/appinsights.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-111

#112 juror: add trust proxy setting
  server/config/express.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-112

#113 add stg environment var
  charts/juror-public/values.stg.template.yaml
Labels: ns:juror, prd:juror, rel:juror-public-pr-113

#118 JDB-5491-2 - Additional session data logging / session save
  server/routes/steps/06-assistance/assistance.controller.js
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-public-pr-118

#119 JDB-5542 - Refactor hearingDate format / DOB submit
  server/lib/utils.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-119

#123 JDB-5546 - FE Config files
  config/development.json
  config/production.json
  config/test.json
Labels: ns:juror, prd:juror, rel:juror-public-pr-123

#124 JDB-5516 - Update Node to v20
  .nvmrc
  Dockerfile
  package.json
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-public-pr-124

#125 update_codeowners
  .github/CODEOWNERS
Labels: ns:juror, prd:juror, rel:juror-public-pr-125

#134 JDB-5549 - Update grunt-contrib-Imagemin
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-public-pr-134

#136 correct startup
  Dockerfile
  package.json
Labels: ns:juror, prd:juror, rel:juror-public-pr-136
