Repository hmcts/juror-public, pull requests merged in 2024-08, with the labels that each got.

#235 Stabilisation8 release
  server/app.js
  server/components/logger/index.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-235

#236 changes to catch termination
  Dockerfile
  server/app.js
  server/lib/appinsights.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-236

#238 Stabilisation9
  Dockerfile
  server/app.js
  server/config/express.js
  server/lib/appinsights.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-238

#239 JM-8023 - Failed response submission logging
  server/routes/steps/07-confirm-information/confirm-information.controller.js
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-public-pr-239

#242 Stabilisation11
  package.json
  server/config/express.js
  server/routes/steps/07-confirm-information/confirm-information.controller.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-public-pr-242

#244 when a juror is entering deferral dates in the public app we need to force DD/MM/YYYY
  server/config/validation/custom-validation.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-244

#245 Stabilisation13
  server/config/validation/custom-validation.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-245
