Repository hmcts/juror-public, pull requests merged in 2024-09, with the labels that each got.

#247 JM-8183 - Node dependency updates
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-public-pr-247

#251 interim1
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-public-pr-251

#255 JM-8133 - Deferral date validation error messages
  client/js/i18n/cy/VALIDATION.json
  client/js/i18n/en/VALIDATION.json
  server/config/validation/custom-validation.js
  server/config/validation/deferral-dates.js
  server/routes/steps/04-confirm-date/deferr/defer-dates.controller.js
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-public-pr-255
