Repository hmcts/juror-public, pull requests merged in 2025-02, with the labels that each got.

#291 Release5.2
  package.json
Labels: ns:juror, prd:juror

#287 task/JS-101: Update character count translations
  client/js/i18n/cy/CHARACTER_COUNT.json
  client/js/i18n/en/CHARACTER_COUNT.json
  client/templates/branches/02-third-party-reason/index.njk
  client/templates/steps/03-qualify/bail.njk
  client/templates/steps/03-qualify/cjs-employed.njk
  client/templates/steps/03-qualify/convictions.njk
  client/templates/steps/03-qualify/mental-health-capacity.njk
  client/templates/steps/03-qualify/mental-health-sectioned.njk
  client/templates/steps/03-qualify/residency.njk
  client/templates/steps/04-confirm-date/deferr.njk
  client/templates/steps/04-confirm-date/excusal.njk
  client/templates/steps/06-assistance/index.njk
Labels: ns:juror, prd:juror, rel:juror-public-pr-287

#293 Release5.3
  README.md
  client/js/i18n/cy/CHARACTER_COUNT.json
  client/js/i18n/en/CHARACTER_COUNT.json
  client/templates/branches/02-third-party-reason/index.njk
  client/templates/steps/03-qualify/bail.njk
  client/templates/steps/03-qualify/cjs-employed.njk
  client/templates/steps/03-qualify/convictions.njk
  client/templates/steps/03-qualify/mental-health-capacity.njk
  client/templates/steps/03-qualify/mental-health-sectioned.njk
  client/templates/steps/03-qualify/residency.njk
  client/templates/steps/04-confirm-date/deferr.njk
  client/templates/steps/04-confirm-date/excusal.njk
  client/templates/steps/06-assistance/index.njk
  package.json
Labels: ns:juror, prd:juror, rel:juror-public-pr-293
