Repository hmcts/juror-public, pull requests merged in 2025-09, with the labels that each got.

#326 JS-544 - Fix incorrect return url on cookie page
  server/config/express.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-326

#328 JS-556 - Public Expense Calculator '400' error logging
  server/routes/expense-calculator/confirm-information/confirm-information.controller.js
Labels: ns:juror, prd:juror, rel:juror-public-pr-328

#327 Release5.13
  package.json
  server/routes/expense-calculator/confirm-information/confirm-information.controller.js
  webpack/htmlWebpack.js
  yarn-audit-known-issues
Labels: ns:juror, prd:juror, rel:juror-public-pr-327

#337 Task/JS-557: Update dependencies
  .nvmrc
  package.json
  server/config/express.js
  yarn.lock
Labels: ns:juror, prd:juror, rel:juror-public-pr-337
